export default interface ApiInstitutionData {
  ID: string,
  NAME?: string,
  SPECGRPN?: string,
  CITY?: string,
  COUNTY?: string,
  STNAME?: string,
  ZIP?: string,
  OFFICES?: number,
  WEBADDR?: string,
  DEPDOM?: number,
  NETINC?: number,
  CERT?: number,
  STALP?: string,
  ASSET?: number,
  DATEUPDT?: string,
  ROA?: number,
  ACTIVE?: number,
  DEP?: number,
  CBSA?: string,
  ADDRESS?: string,
  ADDRESS2?: string,
  FED_RSSD?: string
}