export default interface ApiInstitutionData {
  id: string,
  zip?: string,
  STNAME?: string,
  DEPDOM?: number,
  NETINC?: number,
  CERT?: number,
  STALP?: string,
  ASSET?: number,
  OFFICES?: number,
  CITY?: string,
  DATEUPDT?: string,
  WEBADDR?: string,
  COUNTY?: string,
  ROA?: number,
  NAME?: string,
  ACTIVE?: number,
  DEP?: number,
  CBSA?: string,
}