export default interface ApiInstitutionData {
  id: string,
  name?: string,
  specgrpn?: string,
  city?: string,
  county?: string,
  stname?: string,
  zip?: string,
  offices?: number,
  webaddr?: string,
  depdom?: number,
  netinc?: number,
  cert?: number,
  stalp?: string,
  asset?: number,
  dateupdt?: string,
  roa?: number,
  active?: number,
  dep?: number,
  cbsa?: string,
  address?: string,
  address2?: string,
  fed_rssd?: string
}